name = "Phylodendron2"
uuid = "c1f549d9-9988-42e2-b1fa-c419eb84f933"
authors = ["E Ascarrunz"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
